### ISSUE TITLE
Create a Sharing System

### ISSUE THREAD

**Issue by razwan** [pixelgrade/nova-blocks#254]
Original proposal by @georgeolaru for Pixelgrade.com:
---

[![Sharing modal](https://user-images.githubusercontent.com/1632775/99506602-f9511b80-298a-11eb-9e37-9e5971bae279.png)](https://www.figma.com/file/x3hxMaLar6GA2ZtDOHjO7q/LT-Pattern-Library?node-id=437%3A1)

## Guidelines
It would be great if we can apply the same "block" treatment that we choose with [Comments](https://github.com/pixelgrade/nova-blocks/issues/253), so we can use this Sharing component on both the Pixelgrade.com site and Rosa2+Nova system.

My main concern is *performance* and *privacy* because many plugins available on WordPress add a load of code for a simple set of links. With this sharing system, I would like to address a basic use-case, with minimal Javascript involved and minimal impact on performance and tracking.

I couldn’t find many resources on this matter, but this [Hacker News](https://news.ycombinator.com/item?id=20622324) discussion could be a good starting point that suggests a few promising solutions, like [Shariff](https://github.com/heiseonline/shariff) or [SocialSharePrivacy](http://heiseonline.github.io/shariff/).

**The Share Modal**
- Styling
	- The overall layout is similar to the **Mobile** version of the menu ([see screenshot](https://user-images.githubusercontent.com/1632775/99499360-711a4880-2981-11eb-9c92-ab7218dfe484.png)). - 
	- The colors should be chosen from the Color Palette, with transparent blacks and whites where it’s needed  
- Structure
	- the Share modal could be an area where other plugins can hook up and add their sharing options (eg. like [Jetpack Sharing](https://jetpack.com/support/sharing/)) 
	- While the “Copy link” should be custom coded by us, the other items and groups could be hardcoded for Pixelgrade.com until we figure out a solution to manage them from the backend.

**The Share List**
- The “Copy link” item
	- The "Copy link" functionality is the most important element as it’s containing the “universal” solution for sharing: *a plain link*. It should be custom coded and displayed at the top of the list:
	- I do like the most the experience from [Basecamp](https://3.basecamp.com/3285391/buckets/730928/recordings/1480829162/publication) ([see recording](https://user-images.githubusercontent.com/1632775/99501103-fa327f00-2983-11eb-9c87-3f8aaf9abc72.gif)) and the autofocus from [Stackexchange](https://stackoverflow.com/questions/114543/how-to-horizontally-center-a-div) ([see recording](https://user-images.githubusercontent.com/1632775/99501281-39f96680-2984-11eb-9565-489f7be41402.gif))
- The Print/PDF items are nice-to-have at this point. If you can find some simple and elegant solutions for them, go for it!
- There might be items that should be available only in some environments (eg. [SMS](https://stackoverflow.com/questions/6480462/how-to-pre-populate-the-sms-body-text-via-an-html-link) on mobiles), and we could simply hide them when we find out more details.

**The Share Buttons**
_I will come back later for the "Share" buttons location and styling, as I had some discussions with @oanafilip and now I have some directions to explore._

---

## Resources
- [Figma Mockups](https://www.figma.com/file/x3hxMaLar6GA2ZtDOHjO7q/LT-Pattern-Library?node-id=437%3A1)
- Tools:
   - [Shariff](https://github.com/heiseonline/shariff) 
- Articles:
	-  [UX Considerations for Web Sharing](https://css-tricks.com/ux-considerations-for-web-sharing/)
	-  [What Percent of Page Views Share on Social Media?](https://www.lukew.com/ff/entry.asp?1852) (2014)
	-  [Hacker News](https://news.ycombinator.com/item?id=20622324) discussion
	   -  [The scourge of web analytics](https://www.stavros.io/posts/scourge-web-analytics/)

## ToDos
Here is how I see this project running:
- [x] Style the modal in the frontend (without the _functionality_ for sharing buttons)
	- [x] Create the "Copy link" component
	- [x] Source a list of SVG icons for sharing options @georgeolaru
- [x] Implement a system for sharing links management
- [ ] Create the functionality to open the modal from multiple places (eg. similar to Search)
- [x] Add the “Share” buttons on Upstairs Blog and Community

**Comment by georgeolaru** [comment]
@razwan can you take a look over the _ToDos_ progress, check whether they are done, and close this issue?

**Comment by razwan** [comment]
@georgeolaru all the todos are completed even though in a slightly different manner. 

The only one that isn't really completed is:
>Create the functionality to open the modal from multiple places (eg. similar to Search)

At the moment, the user needs to add a new Sharing block (with the same config) for every toggle button he would like to have on the page. This feels intuitive to me, more so because the overlay is displayed exactly on top of the button, similar to a contextual menu rather than an overlay. 

The reason the Search overlay can work differently is mainly that it is not a Gutenberg block, allowing us to have more control regarding where it is placed, how it is displayed and what toggles its visibility.

However if we need to add this kind of feature, of toggling the same popup from different places on the page I think we should open a new issue to tackle this.
